version: '3.4'

services:
  agilistaapi:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ConnectionStrings:DB_Conn
    ports:
      - 81:80
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    #volumes:
    ##  - mssql-server-agilista-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1600:1433"
#volumes:
  #mssql-server-agilista-data: {}