version: '3'
services:
  dbtests:
    build: 
        dockerfile: Dockerfile-dbtest 
        context: .
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y"
    ports:
      - "1620:1433"
  migration:
    image: boxfuse/flyway:latest
    container_name: flyway_migration_julie
    volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/bin:/flyway/bin
    entrypoint: ["bash", "/flyway/bin/wait-for-it.sh", "--timeout=30", "db:1433", "--", "flyway"]      
    command: -url=jdbc:sqlserver://db;database=master -user=sa -password=P@ssword1 -target=1.1 -mixed=true migrate
    depends_on:
    - db
    