version: '3.4'

services:
  unittests:
    build: 
      dockerfile: Dockerfile-test 
      context: .
    environment:
      - ConnectionStrings:DB_Conn
    #entrypoint: ["bash","ModelTests/entrypoint-tests.sh", "--timeout=30"] <--never works
    #command: ModelTests/entrypoint-tests.sh <--never works
    depends_on:
      - migration
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y"
    ports:
      - "1620:1433"
  migration:
    image: boxfuse/flyway:latest
    container_name: flyway_migration_julie
    volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/bin:/flyway/bin
    entrypoint: ["bash", "/flyway/bin/wait-for-it.sh", "--timeout=30", "db:1433", "--", "flyway"]      
    command: -url=jdbc:sqlserver://db;database=master -user=sa -password=P@ssword1 -mixed=true migrate
    depends_on:
      - db
    
